import type { ChecklistDefinition, ChecklistItem } from './types'

// Alle Gesprächsformulierungen sind sinngemäße Praxisübertragungen, keine Buchzitate.
function point(
  id: string,
  question: string,
  meaning: string,
  whyItMatters: string,
  signals: string[],
  commonMisinterpretation: string,
  possibleQuestionsOrActions: string[],
  sourceNote: string,
  relatedKnowledge: ChecklistItem['relatedKnowledge'] = 'champion',
): ChecklistItem {
  return {
    id,
    question,
    meaning,
    whyItMatters,
    signals,
    commonMisinterpretation,
    possibleQuestionsOrActions,
    sourceNote,
    relatedKnowledge,
  }
}

// prettier-ignore
export const championChecklist: ChecklistDefinition = {
  id: 'champion',
  eyebrow: 'Einfluss · interne Fürsprache · eigenes Interesse',
  title: 'Champion: Wo ist unsere Evidenz belastbar?',
  lead: 'Zehn unabhängige Prüfbereiche. Kein Etikett und kein Score: Unterscheide Beobachtung, Kundenaussage und Verkäuferannahme.',
  whenToUse: 'Nach Discovery und Stakeholder-Gesprächen, vor wichtigen internen Entscheidungsrunden und bei stockendem Zugang zum Economic Buyer.',
  benefit: 'Du erkennst, ob jemand ein hilfreicher Coach oder ein bereits erprobter interner Unterstützer ist – und welche respektvolle Handlung sinnvoll folgt.',
  items: [
    point('rolle',
      'Kannst du Kontakt, Coach, Champion-Kandidat und erprobten Champion anhand von Evidenz unterscheiden?',
      'Ein freundlicher Kontakt reagiert positiv. Ein Coach liefert hilfreichen Kontext. Ein Kandidat zeigt mögliche Motivation und Einfluss. Ein erprobter Champion vertritt den relevanten Value wirksam auch ohne dich.',
      'Beziehungsqualität allein ist keine interne Überzeugungsarbeit; ein Coach ist trotzdem wertvoll.',
      ['Du kannst die bekannten Handlungen statt bloßer Adjektive nennen.', 'Offene Vermutungen und Bestätigungen sind getrennt.'],
      'Er schreibt täglich und ist begeistert, also muss er unser Champion sein.',
      ['Welche konkrete Handlung hat die Person intern bereits übernommen?', 'Was wissen wir direkt, was stammt nur aus ihrer Aussage?'],
      'Whyte → CHAMPION → Coach or Champion?; Lahoutifard → Chapter Eight → Champions vs. Coaches.'),
    point('einfluss',
      'Hat die Person nachweisbar Einfluss in den für die Entscheidung relevanten Gruppen?',
      'Einfluss meint die Fähigkeit, Debatten oder Entscheidungen wirksam zu prägen; er folgt nicht automatisch aus der Hierarchie.',
      'Ein Titel kann Kompetenz, politisches Kapital und Akzeptanz weder bestätigen noch ersetzen.',
      ['Sie hat frühere bereichsübergreifende Initiativen mitgestaltet.', 'Relevante Entscheider greifen ihre Beiträge erkennbar auf.'],
      'Sie ist VP, also reicht ihre Macht in jedem Fall aus.',
      ['Wer hat ihre Empfehlung bei einer vergleichbaren Initiative aufgegriffen?', 'Wo endet der Einfluss auf andere Bereiche?'],
      'Whyte → CHAMPION → 1. A Champion has power and influence; Power and Influence doesn’t necessarily mean seniority.'),
    point('zugang',
      'Verfügt die Person über Glaubwürdigkeit und realistische Zugangswege zu relevanten Entscheidern und zum Economic Buyer?',
      'Zugang ist mehr als den Namen einer Führungskraft zu kennen. Der Champion kann passende Kontakte, Kontext und eine sachliche Ansprache unterstützen.',
      'Ohne echte Verbindung bleibt die wirtschaftliche Priorisierung unbestätigt.',
      ['Sie kann Verantwortung und Sichtweisen der Entscheider plausibel erklären.', 'Ein Einführungsweg oder gemeinsames Gespräch wird konkret geprüft.'],
      'Die Nennung des EB-Namens ist ein bestandener Champion-Test; ein unmöglicher Soforttermin entlarvt dagegen einen Fake.',
      ['Wann wäre ein Austausch zur Business-Wirkung für die verantwortliche Person passend?', 'Welche Hürden oder alternativen Wege sind legitim?'],
      'Lahoutifard → Chapter Eight → Access to the Economic Buyer; Respect & Credibility; Whyte → CHAMPION → Testing your Champions Power and Influence.',
      'economic-buyer'),
    point('wert',
      'Kann die Person Pain, Kundenwert und relevante Unterschiede unserer Lösung glaubwürdig erklären?',
      'Eine verständliche Value Story verbindet Probleme, nachprüfbare Metrics, Decision Criteria und eine begründete Auswahl.',
      'Ohne gemeinsames Verständnis wird die interne Empfehlung schnell zu einer unhaltbaren Feature-Liste.',
      ['Sie kann Kundennutzen in eigenen Worten erläutern.', 'Einwände führen zu sachlichen Verbesserungen statt zu auswendig gelerntem Pitch.'],
      'Sie war von der Demo begeistert, also überzeugt sie das Buying Committee.',
      ['Welche unserer Aussagen würden bei IT, Fachbereich oder Management Widerspruch auslösen?', 'Lass uns Why buy, why us und why now mit den vorhandenen Belegen prüfen.'],
      'Whyte → CHAMPION → Make Your Champion Pitch Perfect; The Three Why’s; Lahoutifard → Chapter Eight → Test the Champion.',
      'pain-implication'),
    point('intern',
      'Gibt es konkrete Hinweise auf interne Fürsprache, auch wenn wir selbst nicht im Raum sind?',
      'Ein Champion vertritt die Lösung in öffentlichen, privaten oder wettbewerbsbezogenen Gesprächen; Aussagen darüber sind erst Indizien.',
      'Der eigentliche Wert entsteht bei internen Diskussionen ohne externen Seller.',
      ['Interne Einwände werden vom Kunden konkret beschrieben; die Antworten werden gemeinsam vorbereitet.', 'Andere Stakeholder greifen eine begründete Empfehlung auf oder vereinbaren eine Folgerunde.'],
      'Die Person sagt, sie verkauft intern, daher ist interne Advocacy bewiesen.',
      ['Welche Rückfragen oder Gegenargumente sind intern aufgetaucht?', 'Welche beobachtbare nächste Entscheidung oder Teilnahme hat sich daraus ergeben?'],
      'Whyte → CHAMPION → The Public Champion Sell; The Private Champion Sell; The Competitor Champion Sell; Lahoutifard → Chapter Eight → Champions vs. Coaches.'),
    point('motivation',
      'Kennst du ein vom Kunden selbst bestätigtes legitimes Interesse am Projekterfolg?',
      'Vested interest und Personal Win bezeichnen eine plausible Verbindung zwischen Projektergebnis und eigenen, freiwillig geäußerten Zielen.',
      'Ein Motiv stärkt die dauerhafte interne Unterstützung, darf aber nicht vom Seller erfunden werden.',
      ['Die Person beschreibt selbst ein Teamziel, eine Verbesserung oder Verantwortung.', 'Das Interesse passt nachvollziehbar zum Projektwert.'],
      'Wir wissen, dass er befördert werden möchte, nur weil er eine Leitungsrolle innehat.',
      ['Was wäre für Sie persönlich oder für Ihr Team ein gelungenes Projektergebnis?', 'Was würde sich ändern, wenn das Vorhaben nicht zustande kommt?'],
      'Whyte → CHAMPION → 3. A Champions have a vested interest in your success; Lahoutifard → Chapter Eight → Personal Win; The Champion Needs You to Win.'),
    point('test',
      'Habt ihr eine kleine, angemessene Handlung vereinbart und ihr tatsächliches Ergebnis betrachtet?',
      'Tests sind nachvollziehbare Arbeitsbeiträge: einen Business Case besprechen, relevante Stakeholder einladen, Einwände klären oder eine interne Wertargumentation prüfen.',
      'Ein Versprechen lässt sich erst durch sinnvolle Umsetzung und Rückmeldung einordnen.',
      ['Ein realistischer Termin oder Beitrag wurde gemeinsam vereinbart.', 'Aus dem Versuch gibt es ein Ergebnis, eine Hürde oder eine sachliche Korrektur.'],
      'Vertrauliche Unterlagen, Konkurrenzangebote oder Erreichbarkeit nach Feierabend seien notwendige Loyalitätsbeweise.',
      ['Wäre es sinnvoll, die Value Story gemeinsam mit der Fachleitung zu prüfen?', 'Was hat die vereinbarte Aktion ergeben, und welche Hürde ist sichtbar geworden?'],
      'Whyte → CHAMPION → Testing Champions; Lahoutifard → Chapter Eight → Test the Champion.'),
    point('befaehigung',
      'Hilfst du der Person, intern eigenständig und mit passenden Belegen zu argumentieren?',
      'Befähigung heißt: Pain, Metrics, Differenzierung und die drei Why-Fragen gemeinsam verstehen, nicht unkommentiert Folien weiterleiten.',
      'Glaubwürdige interne Fürsprache braucht Kundensprache und belastbare Antworten auf Einwände.',
      ['Die Person kann Warum überhaupt, warum diese Lösung und warum jetzt erklären.', 'Offene Fragen wurden mit belegten Beispielen statt erfundenem ROI bearbeitet.'],
      'Ein versandtes Präsentationsdeck ist gleichbedeutend mit einer überzeugenden internen Argumentation.',
      ['Welche Folie würden Sie intern nicht zeigen – und warum?', 'Welche drei Aussagen müssen vor der nächsten Entscheidung belastbar sein?'],
      'Whyte → CHAMPION → Educate your Champion on MEDDICC; Make Your Champion Pitch Perfect; The Three Why’s; Lahoutifard → Chapter Eight → Test the Champion.',
      'metrics'),
    point('stakeholder',
      'Kennst du andere einflussreiche Stakeholder, Gegeninteressen und gegebenenfalls weitere Champions?',
      'Je nach Größe und Entscheidung können technische, fachliche oder wirtschaftliche Perspektiven getrennte interne Unterstützer erfordern.',
      'Ein engagierter IT-Kontakt allein garantiert keinen bereichsübergreifenden Konsens.',
      ['Betroffene Gruppen und mögliche Gegenargumente sind benannt.', 'Weitere Unterstützer sind nur dann als Champions bezeichnet, wenn ihr Verhalten es trägt.'],
      'Mehrere Champions lösen politische Risiken automatisch oder sind immer Pflicht.',
      ['Welche Gruppen sehen das Vorhaben anders?', 'Wo könnte eine zusätzliche fachliche oder wirtschaftliche Stimme nötig sein?'],
      'Whyte → CHAMPION → Champion or Champions?; Counter Champion; Lahoutifard → Chapter Eight → Could There Be More Than One Champion?',
      'decision-process'),
    point('grenzen',
      'Kennst du Grenzen des Einflusses sowie die offenen Schritte zu Entscheidung und Unterschrift?',
      'Timing, Zuständigkeiten, EB-Zugang, Personalwechsel, Procurement und Legal können die Wirksamkeit begrenzen.',
      'Ein fachliches Ja des Champions ist weder Budgetfreigabe noch Vertragsabschluss.',
      ['Zugangsbarrieren und nächste verantwortliche Rolle sind sachlich geklärt.', 'Administrative Freigaben werden getrennt vom fachlichen Engagement verfolgt.'],
      'Der Champion sagt Ja, also sind Einkauf, Legal und Zeichnung erledigt.',
      ['Wer gibt die Investition tatsächlich frei?', 'Welche Freigaben und Unterschriften folgen auf die fachliche Entscheidung?'],
      'Whyte → CHAMPION → Champion and Procurement; Champion and Legal; Champion and Go-Live Plan; Lahoutifard → Chapter Eight → Why Do You Need a Champion?',
      'paper-process'),
  ],
  sourceNotes: [
    'Andy Whyte, MEDDICC → CHAMPION → The Criteria of a Champion, Testing Champions, Build Your Champion sowie Champion and Procurement/Legal.',
    'Darius Lahoutifard, Always Be Qualifying → Chapter Eight – Champion → Access to the Economic Buyer, Respect & Credibility, Personal Win, Champions vs. Coaches, Building Champions, Test the Champion.',
    'Die Whyte-Kriterien sind seine drei expliziten Merkmale; Lahoutifards differenzierte Perspektive ist keine identische universelle Prüfliste.',
    'Die Fragen, das Evidenzprinzip und die Grenze gegen vertrauliche Interna sowie Freizeit-Erreichbarkeit sind eigenständige Praxisableitungen, keine wörtlichen Autorenregeln.',
    'Häkchen leben nur im aktuellen Browser-Arbeitsspeicher: weder Deal-Score noch Speicherung oder Freigabeautomatik.',
  ],
}

// prettier-ignore
export const championKnowledge = {
  title: 'Champion: Nicht Sympathie, sondern Wirkung zählt',
  lead: 'Erkenne echte interne Fürsprache, entwickle einen Coach respektvoll weiter und prüfe, welche Beobachtung deinen nächsten Schritt trägt.',
  shortDefinition: 'Ein Champion unterstützt eine Lösung aufgrund eines eigenen legitimen Interesses, besitzt relevanten Einfluss und vertritt ihren Kundenwert auch dann, wenn du nicht im Raum bist. Ob das gelingt, muss im konkreten Buying Process geprüft werden.',
  benefit: 'Du verwechselst freundliche Unterstützung seltener mit tatsächlichem Einfluss und kannst den nächsten gemeinsamen Schritt gezielt vorbereiten.',
  whyImportant: [
    'Viele entscheidende Kundengespräche finden ohne den Anbieter statt.',
    'Der Einfluss einer Person zeigt sich in tatsächlichen Handlungen, nicht im Titel.',
    'Ein hilfreicher Coach ist wertvoll, selbst wenn er nie zum Champion wird.',
  ],
  roles: [
    { title: 'Kontakt', meaning: 'Ist erreichbar und interessiert; eine aktive Rolle im Entscheidungsprozess ist noch nicht erkennbar.', evidence: 'Interesse oder Reaktion – noch keine interne Advocacy.' },
    { title: 'Coach', meaning: 'Hilft mit Orientierung, Fragen und organisatorischem Kontext. Kann auch ohne Entscheidungsmacht sehr wertvoll sein.', evidence: 'Hilfreiche Informationen oder sachlicher Rat.' },
    { title: 'Champion-Kandidat', meaning: 'Hat mögliche Glaubwürdigkeit, Motivation und Zugang. Interne Wirksamkeit wird noch geprüft.', evidence: 'Plausible Signale, aber noch keine ausreichende Handlungsevidenz.' },
    { title: 'Erprobter Champion', meaning: 'Einfluss, konkrete interne Fürsprache und eigenständiges Interesse sind über passende Handlungen nachvollziehbar.', evidence: 'Belegte Schritte, bestätigte Folgen und weiterhin offene Grenzen.' },
  ],
  whyteCriteria: championChecklist.items.filter((item) => ['einfluss', 'intern', 'motivation'].includes(item.id)),
  additionalPerspective: [
    { title: 'Glaubwürdigkeit und Respekt', meaning: 'Wessen Urteil hat in den betroffenen Gruppen Gewicht? Auch eine niedrigere Rolle kann intern anerkannt sein.' },
    { title: 'Zugang zum Economic Buyer', meaning: 'Kennt die Person realistische Kontaktwege und kann den wirtschaftlichen Kontext vermitteln? Ein Name reicht nicht.' },
    { title: 'Gute Arbeitsbeziehung', meaning: 'Vertrauen und konstruktiver Austausch helfen. Freundschaft oder häufige Nachrichten sind kein Beweis von Advocacy.' },
    { title: 'Personal Win', meaning: 'Frage nach einem vom Kunden selbst beschriebenen Nutzen wie erfolgreicher Umsetzung, Teamverbesserung oder verantworteter Veränderung.' },
  ],
  enablement: [
    'Gemeinsam Pain und relevante, kundenseitig validierte Metrics verstehen.',
    'Eine einfache Value Story in der Sprache der internen Zielgruppe üben: Warum überhaupt kaufen? Warum diese Lösung? Warum jetzt?',
    'Gegenargumente aus Fachbereich, IT und Management offen prüfen und sachlich beantworten.',
    'Einen passenden nächsten Beitrag gemeinsam vereinbaren, ohne vertrauliche Informationen zu fordern.',
  ],
  tests: [
    { title: 'Einfluss beobachten', action: 'Eine bereichsübergreifende Gesprächsrunde oder Rückkopplung zu Decision Criteria mittragen.', caution: 'Terminrestriktionen und Zuständigkeiten sind keine automatische Disqualifikation.' },
    { title: 'Interne Fürsprache einordnen', action: 'Nach tatsächlichen Rückfragen oder Einwänden aus internen Gesprächen fragen; Resultate separat prüfen.', caution: 'Die Aussage „ich habe intern verkauft“ allein ist noch kein externer Beleg.' },
    { title: 'Interesse ergründen', action: 'Nach dem persönlich relevanten Projektergebnis fragen und dessen Bedeutung nicht vorschnell interpretieren.', caution: 'Keine Karriereziele, Boni oder verdeckte Anreize unterstellen.' },
  ],
  buyerAndCommittee: [
    'Champion und Economic Buyer können sich überschneiden, sind aber nicht gleichzusetzen.',
    'EB-Zugang ist wertvoll; kulturelle und organisatorische Hürden müssen sachlich untersucht werden.',
    'Technische, fachliche und wirtschaftliche Fürsprecher können unterschiedliche Gruppen erreichen. Mehrere Champions sind möglich, nicht pauschal vorgeschrieben.',
    'Gegeninteressen oder ein Counter Champion verdienen eine offene, sachliche Analyse.',
    'Ein Champion hilft bei Procurement und Legal, ersetzt aber weder rechtliche Prüfung noch Zeichnungsberechtigung.',
  ],
  redFlags: [
    { claim: '„Er schreibt täglich – unser Champion!“', explanation: 'Kontaktfrequenz kann ein guter Austausch sein. Einfluss, internes Verkaufen und Motivation bleiben offen.' },
    { claim: '„Sie ist VP – genug Macht bewiesen.“', explanation: 'Prüfe statt Organigramm-Titel die Akzeptanz und Wirkung ihrer Vorschläge in den relevanten Gruppen.' },
    { claim: '„Er kennt den EB-Namen – Champion-Test bestanden.“', explanation: 'Ein Name ist weder ein Zugangsweg noch eine bestätigte wirtschaftliche Priorität.' },
    { claim: '„Er sagt, er verkauft intern – Fall abgeschlossen.“', explanation: 'Trenne seine Aussage von beobachtbaren Folgen: Fragen, Termine, Entscheidungen und Gegenargumenten.' },
    { claim: '„Kein EB-Termin – also Fake-Champion.“', explanation: 'Zuständigkeit, Timing und Unternehmenskultur können den Zugang begrenzen. Prüfe Alternativen.' },
    { claim: '„Die Beförderung ist sein Personal Win.“', explanation: 'Ohne eigene Kundenaussage ist das eine Verkäuferprojektion.' },
    { claim: '„Ein erfolgreicher POC und ein IT-Fürsprecher genügen.“', explanation: 'Fachliche, wirtschaftliche und administrative Entscheidungsschritte bleiben gesondert zu qualifizieren.' },
  ],
  scenario: {
    label: 'Frei konstruiertes CRM-/SaaS-Beispiel. Sämtliche Personen, Aussagen, Handlungen und Ergebnisse sind erfunden.',
    steps: [
      { role: 'Kontakt → Coach', detail: 'Ein engagierter CRM-Projektleiter sendet technische Informationen und beantwortet Fragen. Das ist nützliche Orientierung; interne Fürsprache und EB-Zugang sind nicht belegt.', next: 'Nach dem Buying Committee und den relevanten Einwänden fragen, ohne Status zu unterstellen.' },
      { role: 'Coach bleibt Coach', detail: 'Der Projektleiter kann keine Entscheider zusammenbringen. Sein Beitrag bleibt trotzdem wertvoll und muss nicht als Versagen gewertet werden.', next: 'Gemeinsam klären, welche andere Person eine bereichsübergreifende Perspektive besitzt.' },
      { role: 'Zweite Person → Kandidatin', detail: 'Eine fachliche Bereichsleiterin beschreibt einen eigenen Nutzen aus einem besseren CRM-Prozess und bietet an, die Wertargumentation mit Finance abzugleichen.', next: 'Motive offen bestätigen und einen realistischen gemeinsamen Schritt vereinbaren.' },
      { role: 'Kandidatin → erprobte Fürsprecherin', detail: 'Die Bereichsleiterin berichtet von ihrer internen Value-Diskussion ohne Anbieter. Im anschließenden gemeinsamen Termin greift Finance die Argumente eigenständig auf, stellt konkrete Einwände und vereinbart eine weitere Prüfung. Die interne Darstellung bleibt zunächst eine Kundenaussage; das Verhalten von Finance ist separat beobachtbar.', next: 'Reichweite und weitere Schritte prüfen. Eine Finance-Rückfrage und ein Folgetermin belegen noch weder die Budgetzusage noch die gesamte interne Wirkung.' },
    ],
  },
  questions: [
    'Wer außer Ihrem Team muss den geschäftlichen Nutzen nachvollziehen können?',
    'Werden solche Vorhaben bei Ihnen eher fachlich oder wirtschaftlich zuerst diskutiert?',
    'Wie würden Sie den Nutzen intern mit Ihren eigenen Worten erklären?',
    'Welche Einwände erwarten Sie aus IT, Fachbereich oder Finance?',
    'Was wäre für Sie oder Ihr Team ein wirklich gutes Ergebnis dieses Projekts?',
    'Was würden wir brauchen, damit die nächste Gesprächsrunde für alle sinnvoll ist?',
  ],
  practicalTakeaway: 'Frage nicht „Mag mich die Person?“, sondern „Welche Wirkung hat sie schon gezeigt, was weiß ich nur vom Hörensagen und welcher faire nächste Schritt klärt die Lücke?“',
  perspectives: [
    { author: 'Andy Whyte', source: 'MEDDICC → CHAMPION → The Criteria of a Champion; Coach or Champion?; The Public/Private/Competitor Champion Sell; Build Your Champion; The Three Why’s; Testing Champions; Champion and Legal/Procurement.', summary: 'Drei explizite Kriterien: Macht und Einfluss, interne Verkaufsarbeit, vested interest. Für ihn muss jedes Kriterium getestet werden; Freundschaft ist nicht zwingend.' },
    { author: 'Darius Lahoutifard', source: 'Always Be Qualifying → Chapter Eight – Champion → Access to the Economic Buyer; Respect & Credibility; Favorable Relation with You; Personal Win; Champions vs. Coaches; Building Champions; Test the Champion.', summary: 'Stärkerer Fokus auf Respekt, glaubwürdigen EB-Zugang, positive persönliche Beziehung und Personal Win. Diese ergänzenden Merkmale sind nicht einfach Whytes identische Dreierliste.' },
  ],
  sourceNotes: championChecklist.sourceNotes,
} as const
