import type { ChecklistDefinition, ChecklistItem } from './types'

// Gesprächsfragen und CRM-Szenario: eigenständige Praxisübertragung, keine Buchzitate.
function point(
  id: string,
  question: string,
  meaning: string,
  whyItMatters: string,
  signals: string[],
  commonMisinterpretation: string,
  possibleQuestionsOrActions: string[],
  sourceNote: string,
  relatedKnowledge: ChecklistItem['relatedKnowledge'] = 'competition',
): ChecklistItem {
  return {
    id,
    question,
    meaning,
    whyItMatters,
    signals,
    commonMisinterpretation,
    possibleQuestionsOrActions,
    sourceNote,
    relatedKnowledge,
  }
}

// prettier-ignore
export const competitionChecklist: ChecklistDefinition = {
  id: 'competition',
  eyebrow: 'Alternativen · Käuferkriterien · tatsächliche Evidenz',
  title: 'Competition: Gegen welche Alternative verkaufen wir wirklich?',
  lead: 'Zehn unabhängige Fragen zu konkurrierenden Entscheidungen. Ein Haken ist nur eine flüchtige Denkhilfe – keine Bewertung des Deals.',
  whenToUse: 'Nach erster Discovery, vor POC oder Auswahlentscheidung und immer dann, wenn ein Deal trotz positivem Feedback nicht vorankommt.',
  benefit: 'Du trennst bestätigte Alternativen von Hypothesen, erkennst konkurrierende Prioritäten und leitest eine konkrete nächste Frage ab.',
  items: [
    point('alternativen',
      'Sind alle relevanten Alternativen einschließlich Status quo und anderen Projekten überhaupt benannt?',
      'Wettbewerb umfasst Rival Solutions, Internal Build, Other Projects/Priorities und Inertia; auch mehrere können gleichzeitig relevant sein.',
      'Ein einziges eingeholtes Angebot sagt nichts über andere Ressourcenentscheidungen.',
      ['Bestätigte Kundenaussage: Die zuständige Person benennt echte Auswahloptionen.', 'Offene Hypothese: Weitere Initiativen erscheinen plausibel, sind aber noch nicht verifiziert.'],
      'Wir sind der einzige Vendor im Gespräch, also gibt es keine Competition.',
      ['Welche Wege stehen außer unserer Lösung zur Debatte?', 'Was geschieht, falls Sie dieses Vorhaben nicht umsetzen?'],
      'Whyte → COMPETITION → Types of Competition; Lahoutifard → Chapter Two → Where do we cover the Competition?'),
    point('rival',
      'Ist eine konkrete Rival Solution in dieser Entscheidung belegt – oder nur am Markt bekannt?',
      'Prüfe Angebote, Vergleichskriterien und tatsächliche Beteiligung anderer Anbieter, ohne Marktpräsenz als Deal-Tatsache auszulegen.',
      'Unbelegte Feature-Vergleiche lenken vom kaufrelevanten Value ab.',
      ['Beleg: Ein Kunde beschreibt den laufenden Vergleich einschließlich Entscheidungsgegenstand.', 'Ungeprüft: Ein Anbieter ist bei ähnlichen Unternehmen verbreitet.'],
      'Ein Marktführer konkurriert bestimmt in genau diesem Deal.',
      ['Welche alternativen Angebote oder Produkte bewerten Sie tatsächlich?', 'Welche Unterschiede sind für Ihre Entscheidung wichtig, und wie werden sie geprüft?'],
      'Whyte → COMPETITION → Rival Solutions; Lahoutifard → Chapter Five → Decision Criteria.',
      'decision-criteria'),
    point('inertia',
      'Ist geklärt, warum Beibehaltung des Ist-Zustands oder No Decision attraktiv sein könnte?',
      'Status quo hält bestehende Abläufe aufrecht; No Decision bezeichnet eine ausbleibende Investitionsentscheidung. Beides kann sich überschneiden.',
      'Wenig Pain, unklare Metrics oder fehlender Entscheidungsweg sind Warnsignale, keine automatische Lost-Prognose.',
      ['Kundenaussage: Der aktuelle Prozess reicht vorläufig aus.', 'Verifizierter Termin/Prozess: Die Entscheidung wurde tatsächlich verschoben; Grund und Konsequenz sind geklärt.'],
      'Ein abgesagter Termin beweist, dass der Kunde niemals entscheiden wird.',
      ['Was funktioniert heute gut genug, um daran festzuhalten?', 'Welche Konsequenzen entstehen, falls Sie dieses Jahr nichts verändern?'],
      'Whyte → COMPETITION → Inertia; Signs your Deal is Heading for Inertia; Lahoutifard → Chapter Two → Where do we cover the Competition?',
      'pain-implication'),
    point('build',
      'Ist Internal Build eine tatsächliche Option und kennst du technische wie politische Motive?',
      'Eigenentwicklung kann Kontrolle, IP, Anpassbarkeit, Ressourcenfragen oder interne Verantwortlichkeiten betreffen.',
      'Eine pauschal behauptete Kostenüberlegenheit von Buy ist kein belegter Business Case.',
      ['Bestätigte Kundenaussage: Eine IT-Verantwortliche beschreibt Auftrag, Sponsor oder Kapazitätsplanung.', 'Unbestätigt: Der Seller vermutet Eigenbau allein aufgrund der IT-Größe.'],
      'Interne Entwicklung ist grundsätzlich langsamer und teurer.',
      ['Welche Gründe sprechen aus Ihrer Sicht für eine eigene Entwicklung?', 'Wer würde Umfang, Ressourcen und Ergebnis der Eigenentwicklung verantworten?'],
      'Whyte → COMPETITION → Building Internally.',
      'decision-process'),
    point('prioritaeten',
      'Sind andere Initiativen bekannt, die dasselbe Budget, Personal oder Management-Zeit beanspruchen?',
      'Ein Projekt kann auch gegen andere Investitionsvorhaben verlieren, ohne dass ein anderer Softwareanbieter gewinnt.',
      'Die wirtschaftliche Priorität muss kundenseitig entschieden werden.',
      ['Kundenaussage: Ressourcen werden konkret zwischen Vorhaben priorisiert.', 'Offen: Der Seller kennt ein paralleles Projekt, aber nicht den Ressourcenkonflikt.'],
      'Das Budget ist geplant, also ist die Umsetzung bereits priorisiert.',
      ['Welche Vorhaben benötigen dieselben Teams oder Mittel?', 'Wer bewertet die Priorität der Vorhaben und nach welchen Ergebnissen?'],
      'Whyte → COMPETITION → Other Projects/Priorities.',
      'economic-buyer'),
    point('politisch',
      'Kennst du politische Interessen, eigene und gegnerische Champions sowie ihre beobachtbare Wirkung?',
      'Die Political-Perspektive fragt nach Macht, Sponsorschaft und Gegeninteressen, nicht nur nach Organigrammen.',
      'Ein sympathischer Kontakt ist kein beweiskräftiger Champion.',
      ['Beobachtet: Ein Stakeholder bringt eine belastbare Value Story in eine Entscheidung ein.', 'Berichtet: Eine Person behauptet, der interne Build-Sponsor habe bereits zugesagt; unabhängige Bestätigung fehlt.'],
      'Unser Kontakt ist begeistert und damit intern überlegen.',
      ['Wer unterstützt welche Alternative aus welchem nachvollziehbaren Grund?', 'Welche Rückmeldungen aus dem Entscheidungsgremium sind tatsächlich beobachtbar?'],
      'Whyte → COMPETITION → Competitive Strategy; A word from Jack on Competition; Lahoutifard → Chapter Two and Chapter Eight → Champion.',
      'champion'),
    point('kriterien',
      'Sind Decision Criteria, Herkunft und Gewichtung durch den Kunden bestätigt?',
      'Kriterien können von unterschiedlichen Stakeholdern und auch konkurrierenden Anbietern geprägt sein; relevant ist die tatsächliche Käuferentscheidung.',
      'Eine RFP-Liste ist nicht automatisch vollständig, neutral oder unveränderlich.',
      ['Bestätigung: Kriterien werden mit Entscheidern auf Relevanz und Prüfmethode abgeglichen.', 'Ungeprüft: Eine interne Demo-Punkteliste wird bereits als verbindliche Käuferwertung behandelt.'],
      'Technisch besser laut unserer Demo heißt automatisch kaufentscheidend.',
      ['Wer hat diese Kriterien festgelegt, und wozu sind sie wichtig?', 'Wie prüfen Sie die Kriterien im Entscheidungsprozess?'],
      'Whyte → DECISION CRITERIA; Lahoutifard → Chapter Five → Decision Criteria.',
      'decision-criteria'),
    point('value',
      'Unterscheidest du belegten VALUE, DANGER, PARITY und offene Annahmen?',
      'VALUE: Kunde verlangt es, wir erfüllen es, betrachtete Alternative nicht. DANGER umgekehrt. UNIQUE DIFFERENTIATORS werden aktuell nicht verlangt; PARITY erfüllen beide.',
      'Unverifizierte Fremd-Features oder generische eigene Vorteile begründen keine Value-Zone.',
      ['Belegt: Käuferkriterium und Erfüllung beider betrachteten Lösungen wurden konkret validiert.', 'Unbekannt: Es gibt keinen Nachweis über die Fähigkeit des Wettbewerbers.'],
      'Ein einzigartiges Feature ist automatisch VALUE; eine Vermutung über den Rivalen automatisch DANGER.',
      ['Welches konkrete Ergebnis hängt an diesem Kriterium?', 'Wie könnten wir gemeinsam überprüfen, welche Alternative es tatsächlich erfüllt?'],
      'Lahoutifard → Chapter Five → The Value Triangle; Analysis of The Decision Criteria Triangle; Most important zones.',
      'decision-criteria'),
    point('impact',
      'Sind Pain, Metrics und Proof-Points stark genug für eine wirtschaftliche Priorisierung?',
      'Differenzierung verbindet Pain, kundenrelevante Kriterien, belegte Leistungsfähigkeit und validierten Business Impact.',
      'Ein niedriger Rival-Preis belegt ebenso wenig die Kaufentscheidung wie ein beeindruckender Funktionsumfang.',
      ['Bestätigte Kundenaussage: Die verantwortliche Person erläutert die Konsequenz des Problems.', 'Nachvollziehbarer Nachweis: Metrik, Datenquelle und Bewertungsmethode wurden vom Kunden geprüft.'],
      'Unsere Demo war besser und damit ist unser ROI bewiesen.',
      ['Welche Auswirkungen hat das Problem heute auf Ihre Ziele?', 'Welche Nachweise benötigt die wirtschaftlich verantwortliche Person, um Alternativen zu vergleichen?'],
      'Whyte → COMPETITION → Rival Solutions, Other Projects/Priorities; Lahoutifard → Chapter Three → Metrics.',
      'metrics'),
    point('aktion',
      'Ist die wichtigste Competition-Unbekannte mit einer fairen nächsten Validierung geklärt oder terminiert?',
      'Aus Unsicherheit wird eine offene, respektvolle Frage an die richtige Kundengruppe, keine Angstkampagne gegen andere Lösungen.',
      'Trap-Setting ohne Beleg oder vertrauliche Details beschädigt Glaubwürdigkeit.',
      ['Beobachtbar: Eine konkrete Person und ein sachlicher Prüfschritt wurden vereinbart.', 'Offen: Eine Verkäufervermutung wurde noch nicht mit dem Kunden diskutiert.'],
      'Um zu gewinnen, müssen wir die Konkurrenz schlechtmachen oder Geheimunterlagen besorgen.',
      ['Welche offene Frage würde Ihre Entscheidung am stärksten voranbringen?', 'Mit wem sollten wir diese Anforderung und ihren Business Value prüfen?'],
      'Whyte → COMPETITION → Do Not Knock the Competition, Competitive Strategy; eigene ethische Praxisgrenze.'),
  ],
  sourceNotes: [
    'Andy Whyte, MEDDICC → COMPETITION → Types of Competition, Rival Solutions, Building Internally, Other Projects/Priorities, Inertia, Competitive Strategy, Do Not Knock the Competition.',
    'Darius Lahoutifard, Always Be Qualifying → Chapter Two → Where do we cover the Competition?; Chapter Five → The Value Triangle; Chapter Eight → Champion. Das Buch hat kein eigenständiges Competition-Kapitel.',
    'Political / Technical / Commercial sind Analyseperspektiven, keine drei neuen Arten der Competition.',
    'Offene Fragen, Evidenzlabels und faire Einschränkungen von Trap-/Counter-Trap-Fragen sind eigene B2B-Sales-Praxisableitungen. Kein wörtliches Buchzitat.',
    'Häkchen werden weder gespeichert noch bewertet. Die Checklist ersetzt keine kundenseitige Entscheidung.',
  ],
}

// prettier-ignore
export const competitionKnowledge = {
  title: 'Competition: Die echte Alternative verstehen',
  lead: 'Prüfe, welche Lösung, Priorität oder Entscheidung dein Vorhaben tatsächlich verdrängen kann. Auch ohne Konkurrenzangebot gibt es Alternativen.',
  shortDefinition: 'Competition ist jede relevante Alternative, die um dieselbe Kundenentscheidung, dieselben finanziellen Mittel, Ressourcen oder Prioritäten konkurriert. Mehrere Alternativen können zugleich bestehen.',
  benefit: 'Du erkennst, gegen was du tatsächlich verkaufst, und entwickelst nachvollziehbare Differenzierung statt Feature-Battles.',
  whyImportant: [
    'Ein einziger angesprochener Anbieter bedeutet nicht: keine Competition.',
    'Interne Entwicklung, andere Projekte und Inertia können genauso relevant sein wie Rival Solutions.',
    'Ungeprüfte Verkäufervermutungen ersetzen niemals Aussagen oder Entscheidungen des Kunden.',
  ],
  types: [
    { id: 'rival', title: 'Rival Solutions', meaning: 'Konkrete andere Anbieter oder Lösungen um dieselbe Auswahl.', question: 'Welche Angebote werden tatsächlich evaluiert?', trap: 'Ein Marktteilnehmer ist nicht automatisch in diesem Deal aktiv.', action: 'Käuferkriterien und nachprüfbare Differenzierung ermitteln.' },
    { id: 'build', title: 'Building Internally / Internal Build', meaning: 'Eine interne Umsetzung kann aus technischen und politischen Gründen attraktiv sein.', question: 'Was macht die eigene Entwicklung für Sie interessant?', trap: 'Eigenbau ist nicht automatisch teurer oder schlechter.', action: 'Motiv, Sponsor, Ressourcen und Prüfmaßstab erfragen.' },
    { id: 'projects', title: 'Other Projects / Priorities', meaning: 'Andere Investitionen beanspruchen Budget, Fachkräfte oder Aufmerksamkeit.', question: 'Welche anderen Vorhaben konkurrieren um dieselben Kapazitäten?', trap: 'Vorhandenes Budget ist noch keine verbindliche Priorisierung.', action: 'Investitionslogik und Entscheidungsautorität prüfen.' },
    { id: 'inertia', title: 'Inertia / Status quo', meaning: 'Die Organisation hält am Bestehenden fest oder trifft keine neue Investitionsentscheidung.', question: 'Was spricht aus Ihrer Sicht dafür, den jetzigen Zustand beizubehalten?', trap: 'No Decision ist nicht identisch mit einem anderen Vendor-Verlust.', action: 'Why change, Kundennutzen und echte Dringlichkeit validieren.' },
  ],
  evidence: [
    { title: 'Beobachtung / geprüfter Vorgang', meaning: 'Beispiel: Ein tatsächliches Entscheidungsgremium bestätigt eine Verschiebung. Belege und Zeitpunkt dokumentieren.' },
    { title: 'Kundenaussage', meaning: 'Beispiel: Die IT nennt Eigenentwicklung als Option. Das ist ein Bericht, noch kein genehmigtes Build-Projekt.' },
    { title: 'Seller-Hypothese', meaning: 'Beispiel: Der Bestandsanbieter könnte verteidigen. Plausibel, aber nicht als aktive Evaluation bestätigt.' },
    { title: 'Unbekannt', meaning: 'Beispiel: Unklar, ob ein paralleles Programm dieselben IT-Kapazitäten beansprucht. Rückfrage statt Behauptung.' },
  ],
  perspectives: [
    { title: 'Political', meaning: 'Wer hat Einfluss, ein legitimes Interesse oder einen Champion? Wer steht hinter interner Entwicklung oder dem Nicht-Handeln?' },
    { title: 'Technical', meaning: 'Welche kundenseitigen Decision Criteria gelten, und was ist bei jeder relevanten Alternative tatsächlich verifiziert?' },
    { title: 'Commercial', meaning: 'Welche Metrics, Pain-Konsequenzen, Budgets und Ressourcen begründen eine konkrete wirtschaftliche Priorität?' },
  ],
  differentiation: [
    'Ausgangspunkt: kundenseitig beschriebener Pain und gewünschter Outcome.',
    'Das dazu passende Decision Criterion mit fachlichen und wirtschaftlichen Entscheidern validieren.',
    'Die eigene Stärke anhand nachvollziehbarer Proof-Points zeigen; Fremdfähigkeiten nicht erfinden.',
    'Metrics und Business Impact vom Kunden prüfen lassen, statt ROI zu behaupten.',
    'Dem Champion eine faire Value Story für die tatsächliche Entscheidung ermöglichen.',
  ],
  zones: [
    { id: 'parity', title: 'PARITY', meaning: 'Kunde verlangt das Kriterium; beide betrachteten Lösungen erfüllen es. Kein Differenzierungsbeweis.' },
    { id: 'market-trends', title: 'MARKET TRENDS', meaning: 'Beide Lösungen bieten etwas an, das der Kunde derzeit nicht nachfragt.' },
    { id: 'useless', title: 'USELESS', meaning: 'Die betrachtete Konkurrenz bietet eine Fähigkeit, die der Kunde nicht verlangt und die unsere Lösung nicht bietet.' },
    { id: 'unique-differentiators', title: 'UNIQUE DIFFERENTIATORS', meaning: 'Nur unsere Lösung bietet die Fähigkeit, der Kunde fragt sie aber derzeit nicht nach: noch kein bestätigter VALUE.' },
    { id: 'value', title: 'VALUE', meaning: 'Ein bestätigtes Käuferkriterium wird von uns erfüllt, von der betrachteten Alternative nicht. Nachweis für beide Seiten nötig.' },
    { id: 'danger', title: 'DANGER', meaning: 'Ein bestätigtes Käuferkriterium erfüllt die betrachtete Alternative, unsere Lösung nicht. Ungeprüftes Wissen ist keine DANGER-Zone.' },
    { id: 'custom-needs', title: 'CUSTOM NEEDS', meaning: 'Kunde verlangt das Kriterium, aber weder unsere noch die betrachtete Konkurrenzlösung erfüllt es unmittelbar.' },
  ],
  deepDives: [
    { title: 'Competitive Strategy Plan als interne Denkhilfe', meaning: 'Whyte strukturiert relevante Strengths, Weaknesses, Political, Technical, Commercial, Traps, Counter-Traps, Proof-Points und Education. Das ist eine interne, dealbezogene Reflexion, kein pauschaler Wettbewerbervergleich und hier kein eigenes Microtool.', question: 'Welche überprüfbaren Belege und Gegenargumente sind für diese Kundenentscheidung tatsächlich relevant?' },
    { title: 'Inertia: Warum überhaupt verändern?', meaning: 'Prüfe vorhandene Zufriedenheit, schwachen Pain, fehlende Metrics, ausbleibenden Economic-Buyer-Zugang, unklare Decision Criteria / Decision Process und fehlenden kundenseitigen Compelling Event. Jedes Signal ist ein Prüfhinweis, keine Verlustprognose.', question: 'Was passiert im Geschäft, wenn wir den bestehenden Prozess unverändert lassen?' },
    { title: 'Build vs. Buy: auch eine politische Entscheidung', meaning: 'Eigene IT, Kontrollwunsch, IP, Integration, Zeit und Rollout sind echte Motive. Ein interner Sponsor kann andere Ziele als die Fachbereiche verfolgen. Kosten- und Terminaussagen nur anhand kundenseitiger Daten treffen.', question: 'Wer verantwortet eine interne Variante und welche Ziele soll sie besser erfüllen?' },
    { title: 'Andere Initiativen und knappe Ressourcen', meaning: 'ERP-Umstellung, Migration oder organisatorische Programme können dieselben Expertinnen, Budgets oder Führungskapazitäten benötigen. Nur die Entscheider können Prioritäten und Business Cases bestätigen.', question: 'Welche Vorhaben werden bei Engpässen zuerst mit Ressourcen versorgt?' },
    { title: 'Champion, Gegeninteressen und Beschaffung', meaning: 'Prüfe die Wirkung des eigenen Champions, mögliche gegnerische Sponsoren sowie den Einfluss von Einkauf und Gremien. Eine Aussage über interne Fürsprache bleibt ohne beobachtete Wirkung zunächst ein Indiz.', question: 'Wer kann die Unterschiede und die wirtschaftlichen Folgen intern aus eigener Sicht vertreten?' },
    { title: 'Sachlicher Wettbewerb und Trap-Fragen', meaning: 'Whyte beschreibt Trap Setting und Counter-Traps tatsächlich als Wettbewerbstechniken. Unsere eigene faire Praxisgrenze: nur offene, kundennützliche Fragen, überprüfbare Differenzierung, keine FUD-Behauptungen, Täuschung oder vertraulichen Wettbewerberdaten.', question: 'Welche Anforderung ist für den gewünschten Outcome wichtig, und wie prüfen wir sie fair?' },
  ],
  redFlags: [
    { claim: '„Nur unser Angebot liegt vor – wir sind konkurrenzlos.“', explanation: 'Status quo, Internal Build oder andere Projekte können weiterhin gewinnen.' },
    { claim: '„Unsere Demo war besser – Deal gewonnen.“', explanation: 'Ohne Kundenkriterium und bestätigten Business Impact bleibt das ein Verkäufereindruck.' },
    { claim: '„Ein exklusives Feature ist schon VALUE.“', explanation: 'Ohne kundenseitiges Kaufkriterium ist es höchstens ein UNIQUE DIFFERENTIATOR.' },
    { claim: '„Der Rival-Preis ist niedriger – wir verlieren.“', explanation: 'Preise und Value müssen für den konkreten Kaufentscheid gewichtet und verifiziert werden.' },
    { claim: '„Das RFP ist vollständig objektiv.“', explanation: 'Herkunft, Gewichtung und Einflussmöglichkeiten sachlich prüfen.' },
    { claim: '„Kein EB-Termin – automatisch No Decision.“', explanation: 'Eine Zugangsbarriere ist ein Warnsignal, aber keine sichere Vorhersage.' },
    { claim: '„Budget existiert – höchste Priorität bestätigt.“', explanation: 'Andere Vorhaben können dieselben Mittel und Ressourcen beanspruchen.' },
    { claim: '„Die Konkurrenz kann dieses Feature nicht.“', explanation: 'Ohne Nachweis bleibt es eine ungeprüfte Seller-Hypothese.' },
  ],
  scenario: {
    label: 'Frei konstruiertes B2B-CRM/SaaS-Beispiel: keine echten Kundendaten, Anbieterfunktionen oder Geschäftszahlen.',
    steps: [
      { title: 'Beobachtung', detail: 'In Discovery werden bestehende Excel- und Legacy-Prozesse gemeinsam demonstriert. Der Aufwand ist sichtbar, aber nicht quantifiziert.', next: 'Betroffene Abläufe und Pain-Konsequenzen mit Fachbereich und IT validieren.' },
      { title: 'Kundenaussage', detail: 'Der Fachbereich sagt: „Wir sprechen momentan nur mit euch.“ Die IT erwähnt zugleich eine mögliche interne Lösung.', next: 'Klären, ob der Build-Vorschlag einen Sponsor, Auftrag und Kapazitäten hat.' },
      { title: 'Weitere Aussage', detail: 'Ein Transformationsprogramm könnte dieselben IT-Spezialisten beanspruchen. Ob es tatsächlich Vorrang hat, bleibt offen.', next: 'Priorität und Ressourcen mit der entscheidungsverantwortlichen Person abgleichen.' },
      { title: 'Seller-Hypothese', detail: 'Das Unternehmen könnte die bisherigen Abläufe behalten oder keine neue Investitionsentscheidung treffen.', next: 'Why change, validierte Metrics und Entscheidungsprozess statt vermuteter Dringlichkeit prüfen.' },
      { title: 'Nächster Nachweis', detail: 'Der Champion-Kandidat bietet eine gemeinsame Kriterienrunde an. Das ist ein vereinbarter Schritt, noch keine bewiesene Fürsprache.', next: 'Stakeholder-Ergebnis, wirtschaftliche Relevanz und Alternativen anschließend unabhängig prüfen.' },
    ],
  },
  questions: [
    'Was wäre heute Ihre bevorzugte Alternative, wenn dieses Vorhaben nicht zustande kommt?',
    'Wessen Ressourcen oder Budget werden für diese Entscheidung außerdem benötigt?',
    'Welche Kriterien entscheiden für Ihr Team tatsächlich über den Erfolg?',
    'Welche Folgen des Nicht-Handelns sind intern bereits belegt?',
    'Wer beurteilt den Business Value und die Priorität im Vergleich zu anderen Vorhaben?',
  ],
  practicalTakeaway: 'Kläre erst die wirklichen Alternativen, dann ihre Entscheidungsgründe, dann den mit dem Kunden geprüften Unterschied – und vereinbare eine nächste Evidenzprüfung.',
  sourceNotes: [
    'Andy Whyte, MEDDICC → COMPETITION → Types of Competition, Rival Solutions, Building Internally, Other Projects/Priorities, Inertia, Signs your Deal is Heading for Inertia, Competitive Strategy, The Competitive Strategy Plan, Do Not Knock the Competition.',
    'Andy Whyte → DON’T KNOCK THE COMPETITION → Trap-Setting Questions; beschreibt die Taktik offensiv, nicht als grundsätzlich verboten.',
    'Darius Lahoutifard, Always Be Qualifying → Chapter Two → Where do we cover the Competition?; Chapter Five → The Value Triangle, Analysis of The Decision Criteria Triangle, Most important zones, How to Act on Each Zone?; Chapter Eight → Champion. Kein eigenständiges Competition-Kapitel.',
    'Vier Alternativarten stammen aus Whytes Typologie. Political / Technical / Commercial sind separate Analyseperspektiven.',
    'Evidenzgrenzen, offene Fragen, eigene faire Trap-Praxisgrenze und das CRM-Beispiel sind ausdrücklich eigene Übertragungen beziehungsweise frei konstruierte Illustration.',
  ],
}
